export const APP_USERNAME = "discord-bridge"; // The username of the APP itself.
export const APP_ICON_URL = "https://raw.githubusercontent.com/laserman120/discord-bridge/refs/heads/main/assets/discord_bridge_icon.png";
export const APP_ICON_MODLOG_BLUE = "https://raw.githubusercontent.com/laserman120/discord-bridge/77a826a8572e7adc37cee97799c19dd5aec19cb1/assets/ModLogIconBlue.png";
export const APP_ICON_MODLOG_GREY = "https://raw.githubusercontent.com/laserman120/discord-bridge/77a826a8572e7adc37cee97799c19dd5aec19cb1/assets/ModLogIconGray.png";
export const APP_ICON_MODLOG_RED = "https://raw.githubusercontent.com/laserman120/discord-bridge/77a826a8572e7adc37cee97799c19dd5aec19cb1/assets/ModLogIconRed.png";
export const APP_ICON_MODLOG_GREEN = "https://raw.githubusercontent.com/laserman120/discord-bridge/77a826a8572e7adc37cee97799c19dd5aec19cb1/assets/ModLogIconGreen.png";
export const NEWS_SOURCE_SUBREDDIT = 'Discord_Bridge'; // Subreddit that will be used to post news/announcements about the app.
export const NEWS_SOURCE_AUTHOR = '_GLAD0S_'; // Reddit account that will be used to post news/announcements in the source subreddit.
export const PRUNE_AGE_SECONDS = 13 * 86400; // Age until messages are pruned
export const NEWS_MAX_AGE_MS = 3 * 60 * 60 * 1000; // Max age of news posts to consider for notifications (3 hours)